server:
  port: 8888

spring:
  application:
    name: nacos-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #Nacos服务注册中心地址
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
