server:
  port: 8002
spring:
  application:
    name: provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        heart-beat-interval: 2 # 设置心跳的周期，单位为毫秒，这里将心跳间隔设置为2秒
        heart-beat-timeout: 3 # 设置心跳超时时间，单位为毫秒，这里将心跳超时时间设为3秒，即服务端3秒收不到客户端心跳，会将该客户端注册的实例设为不健康
        ip-delete-timeout: 6 # 设置实例删除的超时时间，单位为毫秒，这里将实例删除超时时间设为6秒，即服务端6秒收不到客户端心跳，会将该客户端注册的实例删除：
